version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 6869
      POSTGRES_DB: netlearn
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  pgdata:
